### PR TITLE
Fix easeTo integration, update example

### LINKED ISSUE #30: Using flyTo for easeTo
We aren't correctly integrating easeTo atm, we are hooking into flyTo instead. See [here](https://github.com/mapbox/flutter-mapbox-gl/blob/master/lib/controller.dart#L116).

cc @seddonm1

### PR DESCRIPTION
**Pull request by tobrun**
closes #30

### CODE REVIEW

File: android/src/main/java/com/mapbox/flutter/FlutterMapboxPlugin.java [hunk 1]
```diff
@@ -150,13 +150,11 @@ public void onMethodCall(MethodCall call, Result result) {
...
       long textureId = textureIdOfCall(call);
       if (maps.containsKey(textureId)) {
-
         CameraPosition cameraPosition = parseCamera(call.argument("camera"));
         int duration = intParamOfCall(call, "duration");
-        boolean easingInterpolator = booleanParamOfCall(call, "easingInterpolator");
 
         MapInstance mapHolder = maps.get(textureId);
-        mapHolder.map.easeTo(cameraPosition, duration, easingInterpolator);
+        mapHolder.map.easeTo(cameraPosition, duration, true);
```
Comment (tobrun) [inline android/src/main/java/com/mapbox/flutter/FlutterMapboxPlugin.java]: removing the boolean easing from the api, is a remainder from a legacy api that needs to be removed.
